---
- name: Install foreman server

  hosts: foreman_app

  become: yes

  roles:

    - nephelaiio.plugins
    - nephelaiio.pip

  vars:

    foreman_admin_user: admin

  tasks:

    - block:

        - name: create foreman operating systems
          foreman_operatingsystem:
            name: "{{ item.name }}"
            family: "{{ item.family }}"
            major: "{{ item.major }}"
            minor: "{{ item.minor | default(omit) }}"
            release_name: "{{ item.release_name | default(omit) }}"
            architectures: "{{ item.architectures | default(omit) }}"
            media: "{{ item.media | default(omit) }}"
            ptables: "{{ item.ptables | default(omit) }}"
            password_hash: "{{ item.password_hash | default('SHA512') }}"
            server_url: "{{ foreman_url }}"
            username: "{{ foreman_admin_user }}"
            password: "{{ foreman_admin_pass }}"
          loop_control:
            label: "{{ item.name }}"
          loop: "{{ foreman_os | default([]) }}"

        - name: enumerate foreman media
          set_fact:
            foreman_media: "{{ foreman_os | selectattr('media', 'defined') | map(attribute='media') | flatten(levels=1) | unique | list }}"

        - name: manage foreman installation media
          foreman_installation_medium:
            name: "{{ item }}"
            locations: "{{ foreman_locations }}"
            organizations: "{{ foreman_organizations }}"
            operatingsystems: "{{ foreman_os | selectattr('media', 'contains', item) | map(attribute='name') | unique | list }}"
            server_url: "{{ foreman_url }}"
            username: "{{ foreman_admin_user }}"
            password: "{{ foreman_admin_pass }}"
          loop: "{{ foreman_media | default([]) }}"

        - name: manage foreman hostgroups
          foreman_hostgroup:
            name: "{{ item.name }}"
            organizations: "{{ item.organizations | default(omit) }}"
            locations: "{{ item.locations | default(omit) }}"
            domain: "{{ item.domain | default(omit) }}"
            subnet: "{{ item.subnet | default(omit) }}"
            architecture: "{{ item.architecture | default(omit) }}"
            media: "{{ item.media | default(omit) }}"
            operatingsystem: "{{ item.operatingsystem | default(omit) }}"
            pxe_loader: "{{ item.pxe_loader | default(omit) }}"
            ptable: "{{ item.ptable | default(omit) }}"
            environment: "{{ item.environment | default(omit) }}"
            puppet_proxy: "{{ item.puppet_proxy | default(omit) }}"
            puppet_ca_proxy: "{{ item.puppet_ca_proxy | default(omit) }}"
            openscap_proxy: "{{ item.openscap_proxy | default(omit) }}"
            parameters: "{{ item.parameters | default(omit) }}"
            root_pass: "{{ item.root_pass | default(omit) }}"
            server_url: "{{ foreman_url }}"
            username: "{{ foreman_admin_user }}"
            password: "{{ foreman_admin_pass }}"
          loop_control:
            label: "{{ item.name }}"
          loop: "{{ foreman_hostgroups | default([]) }}"

      delegate_to: localhost
