---
- name: Install foreman server

  hosts: foreman_app

  become: yes

  roles:

    - nephelaiio.plugins
    - nephelaiio.pip

  vars:

    foreman_admin_user: admin
    foreman_os:
      - name: Ubuntu
        family: Debian
        architecture: x86_64
        major: 18.04
        release_name: bionic
        ptables:
          - "Preseed default"
        provisioning_templates:
          - "Preseed default"
          - "Preseed default finish"
          - "Preseed default PXELinux"
        media:
          - Ubuntu mirror
        password_hash: SHA512
      - name: CentOS
        family: Redhat
        architecture: x86_64
        major: 7
        ptables:
          - "Kickstart default"
        provisioning_templates:
          - "Kickstart default"
          - "Kickstart default finish"
          - "Kickstart default PXELinux"
        media:
          - CentOS mirror
        password_hash: SHA512

  tasks:

    - block:

        - name: create foreman operating systems
          foreman_operatingsystem:
            name: "{{ item.name }}"
            family: "{{ item.family }}"
            major: "{{ item.major }}"
            minor: "{{ item.minor | default(omit) }}"
            release_name: "{{ item.release_name | default(omit) }}"
            architectures: "{{ item.architectures | default(omit) }}"
            media: "{{ item.media | default(omit) }}"
            ptables: "{{ item.ptables | default(omit) }}"
            password_hash: "{{ item.password_hash | default('SHA512') }}"
            server_url: "{{ foreman_url }}"
            username: "{{ foreman_admin_user }}"
            password: "{{ foreman_admin_pass }}"
          loop_control:
            label: "{{ item.name }}"
          loop: "{{ foreman_os }}"

        - name: enumerate foreman media
          set_fact:
            foreman_media: "{{ foreman_os | selectattr('media', 'defined') | map(attribute='media') | flatten(levels=1) | unique | list }}"

        - name: update foreman installation media
          foreman_installation_medium:
            name: "{{ item }}"
            locations: "{{ foreman_locations }}"
            organizations: "{{ foreman_organizations }}"
            operatingsystems: "{{ foreman_os | selectattr('media', 'contains', item) | map(attribute='name') | unique | list }}"
            server_url: "{{ foreman_url }}"
            username: "{{ foreman_admin_user }}"
            password: "{{ foreman_admin_pass }}"
          loop: "{{ foreman_media }}"

      delegate_to: localhost
