---
- name: Install foreman proxy

  hosts: foreman_proxy

  become: yes

  roles:

    - nephelaiio.plugins
    - nephelaiio.pip
    - diodonfrost.puppet_agent
    - foreman_server_repositories
    - haveged
    - foreman_installer

  vars:

  pre_tasks:

  tasks:

    - name: create puppet group
      group:
        name: puppet
        local: yes

    - name: install puppet
      include_role

    - name: install pip requirements
      pip:
        name: apypie

    - name: create foreman domains
      foreman_domain:
        name: "{{ item }}"
        locations: "{{ foreman_locations }}"
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
        dns_proxy: "{{ ansible_fqdn }}"
      loop_control:
        label: "{{ item }}"
      loop: "{{ foreman_domains }}"
      tags:
        - domains
        - configure

    - name: create foreman subnets
      foreman_subnet:
        name: "{{ subnet | ipaddr('network') }}/{{ subnet | ipaddr('prefix') }}"
        network: "{{ subnet | ipaddr('network') }}"
        cidr: "{{ subnet | ipaddr('prefix') }}"
        gateway: "{{ ansible_default_ipv4.gateway }}"
        from_ip: "{{ subnet | ipaddr(foreman_dhcp_from) }}"
        to_ip: "{{ subnet | ipaddr(foreman_dhcp_to) }}"
        dns_primary: "{{ ansible_dns.nameservers[0] }}"
        dns_secondary: "{{ ansible_dns.nameservers[1] | default(omit) }}"
        domains: "{{ foreman_domains }}"
        locations: "{{ foreman_locations }}"
        dhcp_proxy: "{{ ansible_fqdn }}"
        tftp_proxy: "{{ ansible_fqdn }}"
        httpboot_proxy: "{{ ansible_fqdn }}"
        discovery_proxy: "{{ ansible_fqdn }}"
        dns_proxy: "{{ ansible_fqdn }}"
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      vars:
        subnet: "{{ item | ipaddr }}"
      loop:
        - "{{ foreman_subnet }}"
      tags:
        - subnets
        - configure

    - name: activate host discovery
      foreman_setting:
        name: default_pxe_item_global
        value: discovery
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
