---
- name: Install foreman proxy

  hosts: foreman_proxy

  become: yes

  roles:

    - nephelaiio.plugins
    - nephelaiio.pip
    - diodonfrost.puppet_agent
    - foreman_server_repositories
    - haveged
    - foreman_installer

  vars:

    puppet_version: 6

    foreman_proxy_port: 8443
    _foreman_domains:
      - "{{ ansible_domain }}"
      - "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr | ipaddr('revdns') | split_with('.') | tail | join('.') | regex_replace('\\.$', '') }}"
    _foreman_subnets:
      - "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) }}"

  pre_tasks:

    - name: create puppet group
      group:
        name: puppet

  tasks:

    - name: install pip requirements
      pip:
        name: apypie

    - name: create foreman domains
      foreman_domain:
        name: "{{ item }}"
        locations: "{{ foreman_locations }}"
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
        dns_proxy: "{{ ansible_fqdn }}"
      loop_control:
        label: "{{ item }}"
      loop: "{{ foreman_domains | default(_foreman_domains) }}"
      tags:
        - domains
        - configure

    - name: create foreman subnets
      foreman_subnet:
        name: "{{ subnet | ipaddr('network') }}/{{ subnet | ipaddr('prefix') }}"
        network: "{{ subnet | ipaddr('network') }}"
        cidr: "{{ subnet | ipaddr('prefix') }}"
        gateway: "{{ subnet | ipaddr('1') }}"
        from_ip: "{{ subnet | ipaddr('128') }}"
        to_ip: "{{ subnet | ipaddr('254') }}"
        dns_primary: "{{ ansible_dns.nameservers[0] }}"
        dns_secondary: "{{ ansible_dns.nameservers[1] | default(omit) }}"
        domains: "{{ foreman_domain | default(_foreman_domains) }}"
        locations: "{{ foreman_locations }}"
        dhcp_proxy: "{{ ansible_fqdn }}"
        tftp_proxy: "{{ ansible_fqdn }}"
        httpboot_proxy: "{{ ansible_fqdn }}"
        discovery_proxy: "{{ ansible_fqdn }}"
        dns_proxy: "{{ ansible_fqdn }}"
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      vars:
        subnet: "{{ item | ipaddr }}"
      loop: "{{ foreman_subnets | default(_foreman_subnets) }}"
      tags:
        - subnets
        - configure

    - name: activate host discovery
      foreman_setting:
        name: default_pxe_item_global
        value: discovery
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
