---
- name: Install foreman server

  hosts: foreman_app

  become: yes

  roles:

    - nephelaiio.plugins
    - umask
    - koji
    - foreman_server_repositories
    - haveged
    - foreman_installer

  vars:

    foreman_installer_options:
      - --enable-foreman-plugin-ansible
      - --enable-foreman-plugin-cockpit
      - --enable-foreman-plugin-discovery

