---
- name: Install foreman server

  hosts: foreman_app

  become: yes

  roles:

    - nephelaiio.plugins
    - nephelaiio.pip
    - umask
    - koji
    - foreman_server_repositories
    - haveged
    - foreman_installer

  vars:

    foreman_installer_scenario: foreman
    foreman_api_allpages: 9999999999
    foreman_installer_options:
      - "--enable-foreman"
      - "--enable-puppet"
      - "--enable-foreman-cli"
      - "--enable-foreman-cli-ansible"
      - "--enable-foreman-compute-libvirt"
      - "--enable-foreman-compute-ovirt"
      - "--enable-foreman-plugin-templates"
      - "--enable-foreman-plugin-openscap"
      - "--enable-foreman-plugin-discovery"
      - "--foreman-foreman-url {{ foreman_url }}"
      - "--foreman-configure-epel-repo true"
      - "--foreman-configure-scl-repo true"
      - "--foreman-db-adapter postgresql"
      - "--foreman-db-database {{ foreman_db_name }}"
      - "--foreman-db-host localhost"
      - "--foreman-db-manage true"
      - "--foreman-db-manage-rake true"
      - "--foreman-db-username {{ foreman_db_user }}"
      - "--foreman-db-password {{ foreman_db_pass }}"
      - "--foreman-initial-admin-username {{ foreman_admin_user }}"
      - "--foreman-initial-admin-password {{ foreman_admin_pass }}"
      - "--puppet-autosign true"
      - "--puppet-autosign-entries '*.{{ foreman_puppet_autosign_domain }}'"
      - "--enable-foreman-plugin-ansible"
      - "--enable-foreman-proxy"
      - "--enable-foreman-proxy-plugin-ansible"
      - "--foreman-proxy-puppet true"
      - "--foreman-oauth-active true"
      - "--foreman-oauth-consumer-key {{ foreman_oauth_consumer_key }}"
      - "--foreman-oauth-consumer-secret {{ foreman_oauth_consumer_secret }}"
      - "--foreman-proxy-oauth-consumer-key {{ foreman_oauth_consumer_key }}"
      - "--foreman-proxy-oauth-consumer-secret {{ foreman_oauth_consumer_secret }}"
      - "--foreman-server-ssl-ca {{ foreman_server_ssl_ca }}"
      - "--foreman-server-ssl-cert {{ foreman_server_ssl_cert }}"
      - "--foreman-server-ssl-key {{ foreman_server_ssl_key }}"

  tasks:

    - name: install pip requirements
      pip:
        name: apypie

    - name: query foreman users
      uri:
        url: "{{ foreman_url }}/api/users"
        method: GET
        body_format: json
        body:
          per_page: "{{ foreman_api_allpages }}"
        force_basic_auth: yes
        user: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      register: foreman_user_query
      ignore_errors: yes

    - block:

        - name: rake permissions:reset
          command: /usr/sbin/foreman-rake permissions:reset
          register: handler_permissions_reset

        - name: override admin credentials
          set_fact:
            foreman_permissions_reset: true
            reset_admin_user: "{{ ((handler_permissions_reset.stdout | split_with(' '))[3])[0:-1] }}"
            reset_admin_pass: "{{ (handler_permissions_reset.stdout | split_with(' '))[5] }}"

        - name: query foreman users
          uri:
            url: "{{ foreman_url }}/api/users"
            method: GET
            body_format: json
            body:
              per_page: "{{ foreman_api_allpages }}"
            force_basic_auth: yes
            user: "{{ reset_admin_user }}"
            password: "{{ reset_admin_pass }}"
          register: foreman_reset_query

        - name: set admin user facts
          set_fact:
            foreman_admin: "{{ foreman_reset_query.json.results | selectattr('login', 'equalto', foreman_admin_user) |  first }}"
            foreman_reset:
              password: "{{ foreman_admin_pass }}"

        - name: set admin foreman password
          uri:
            url: "{{ foreman_url }}/api/users/{{ foreman_admin.id }}"
            method: PUT
            body_format: json
            body:
              user:
                current_password: "{{ reset_admin_pass }}"
                password: "{{ foreman_admin_pass }}"
                password_confirmation: "{{ foreman_admin_pass }}"
            force_basic_auth: yes
            user: "{{ reset_admin_user }}"
            password: "{{ reset_admin_pass }}"

      when: foreman_user_query is failed

    - name: configure ldap authentication
      foreman_auth_source_ldap:
        name: "{{ foreman_ldap_domain }}"
        server_type: "{{ foreman_ldap_type | default('active_directory') }}"
        host: "{{ foreman_ldap_host }}"
        locations: "{{ foreman_locations }}"
        organizations: "{{ foreman_organizations }}"
        account: "{{ foreman_ldap_cn }}"
        account_password: "{{ foreman_ldap_pass }}"
        attr_login: uid
        attr_firstname: givenName
        attr_lastname: sn
        attr_mail: mail
        base_dn: "{{ foreman_ldap_user_base }}"
        groups_base: "{{ foreman_ldap_group_base }}"
        onthefly_register: yes
        usergroup_sync: yes
        state: present
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      when: foreman_ldap_domain is defined
      tags:
        - auth

    - name: create local admin group
      foreman_usergroup:
        name: "{{ foreman_ldap_admin_group }}"
        admin: yes
        roles:
          - System admin
        state: present
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      when:
        - foreman_ldap_admin_group is defined
      tags:
        - auth

    - name: create ldap admin group
      foreman_external_usergroup:
        name: "{{ foreman_ldap_admin_group }}"
        auth_source_ldap: "{{ foreman_ldap_domain }}"
        usergroup: "{{ foreman_ldap_admin_group }}"
        state: present
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      when:
        - foreman_ldap_domain is defined
        - foreman_ldap_admin_group is defined
      tags:
        - auth

    - name: create ldap users group
      foreman_usergroup:
        name: "{{ foreman_ldap_users_group }}"
        roles:
          - Viewer
        state: present
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      when:
        - foreman_ldap_users_group is defined
      tags:
        - auth

    - name: create local users group
      foreman_external_usergroup:
        name: "{{ foreman_ldap_users_group }}"
        auth_source_ldap: "{{ foreman_ldap_domain }}"
        usergroup: "{{ foreman_ldap_users_group }}"
        state: present
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
      when:
        - foreman_ldap_domain is defined
        - foreman_ldap_users_group is defined
      tags:
        - auth

    - block:

        - name: install puppet openscap module
          command: /opt/puppetlabs/bin/puppet module install theforeman-foreman_scap_client
          changed_when: false

        - name: upgrade puppet openscap module
          command: /opt/puppetlabs/bin/puppet module upgrade theforeman-foreman_scap_client
          changed_when: false

        - name: upload default scap content
          command: /sbin/foreman-rake foreman_openscap:bulk_upload:default
          changed_when: false

      tags:
        - scap
