---
- name: Install project prerequisites

  hosts: localhost

  strategy: linear

  tasks:

    - name: install role requirements
      command: ansible-galaxy role install -r roles/requirements.yml --force

    - name: run ansible galaxy
      command: ansible-galaxy collection install -r roles/requirements.yml --force

    - name: pull git submodules
      command: git submodule update --recursive
      tags:
        - skip_ansible_lint
