---
- name: include role dependencies
  include_role:
    name: "{{ item }}"
  loop:
    - nephelaiio.plugins
    - nephelaiio.pip
    - nephelaiio.foreman_repo
    - diodonfrost.puppet_agent
    - foreman_installer

- name: install pip requirements
  pip:
    name: apypie

- name: activate host discovery
  foreman_setting:
    name: default_pxe_item_global
    value: discovery
    server_url: "{{ foreman_url }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_pass }}"
