---
puppet_version: 6
foreman_proxy_port: 8443
foreman_installer_options:
  - "--no-enable-foreman"
  - "--no-enable-puppet"
  - "--enable-foreman-proxy"
  - "--enable-foreman-proxy-plugin-discovery"
  - "--enable-foreman-proxy-plugin-dns-powerdns"
  - "--foreman-proxy-bind-host 0.0.0.0"
  - "--foreman-proxy-trusted-hosts localhost"
  - "--foreman-proxy-puppet true"
  - "--foreman-proxy-foreman-base-url {{ foreman_url }}"
  - "--foreman-proxy-register-in-foreman true"
  - "--foreman-proxy-bmc true"
  - "--foreman-proxy-dhcp true"
  - "--foreman-proxy-dhcp-interface {{ ansible_default_ipv4.interface }}"
  - "--foreman-proxy-dhcp-network {{ foreman_subnet | ipaddr('network') }}"
  - "--foreman-proxy-dhcp-netmask {{ foreman_subnet | ipaddr('netmask') }}"
  - "--foreman-proxy-dhcp-gateway {{ ansible_default_ipv4.gateway }}"
  - "--foreman-proxy-dhcp-nameservers {{ ansible_dns.nameservers | join(',') }}"
  - "--foreman-proxy-dhcp-range '{{ foreman_subnet | ipaddr(foreman_dhcp_from) | ipaddr('address') }} {{  foreman_subnet | ipaddr(foreman_dhcp_to) | ipaddr('address') }}'"
  - "--foreman-proxy-dns true"
  - "--foreman-proxy-dns-provider powerdns"
  - "--foreman-proxy-plugin-dns-powerdns-backend rest"
  - "--foreman-proxy-plugin-dns-powerdns-rest-api-key {{ foreman_pdns_api_key }}"
  - "--foreman-proxy-plugin-dns-powerdns-rest-url {{ foreman_pdns_url }}/api/v1/servers/localhost"
  - "--foreman-proxy-plugin-discovery-install-images true"
  - "--foreman-proxy-http true"
  - "--foreman-proxy-logs true"
  - "--foreman-proxy-puppet true"
  - "--foreman-proxy-tftp true"
  - "--foreman-proxy-oauth-consumer-key {{ foreman_oauth_consumer_key }}"
  - "--foreman-proxy-oauth-consumer-secret {{ foreman_oauth_consumer_secret }}"
  - "--enable-foreman-proxy-plugin-openscap"
  - "{{ foreman_proxy_trusted_hosts | map('map_format', '--foreman-proxy-trusted-hosts %s') | join(' ') }}"
foreman_proxy_ssl_ca: /etc/puppetlabs/puppet/ssl/certs/ca.pem
foreman_proxy_ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/{{ inventory_hostname }}.pem"
foreman_proxy_ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/{{ inventory_hostname }}.pem"
